name: Go
on: [push, pull_request]
jobs:
  windows:
      runs-on: windows-latest
      strategy:
        matrix:
          go: ['1.15']
      name: Go ${{ matrix.go }} on Windows
      env:
        name: windows
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Test Library
          run: |
            go test ./test

        - name: Build Rm2k Fix Watcher binary
          run: |
            cd cmd/rm2kfixwatcher && go build -v

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: ${{ env.name }}
            path: |
              cmd/rm2kfixwatcher/rm2kfixwatcher.exe

  macos:
      runs-on: macOS-latest
      strategy:
        matrix:
          go: ['1.15']
      name: Go ${{ matrix.go }} on MacOS
      env:
        name: mac
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Test Library
          run: |
            go test ./test

        - name: Build Rm2k Fix Watcher binary
          run: |
            cd cmd/rm2kfixwatcher && go build -v

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: ${{ env.name }}
            path: |
              cmd/rm2kfixwatcher/rm2kfixwatcher

  linux:
      name: Go ${{ matrix.go }} on Ubuntu
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go: ['1.15']
      env:
        name: ubuntu
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Test Library
          run: |
            go test ./test

        - name: Build Rm2k Fix Watcher binary
          run: |
            cd cmd/rm2kfixwatcher && go build -v

        - name: Artifact
          uses: actions/upload-artifact@v2
          with:
            name: ${{ env.name }}
            path: |
              cmd/rm2kfixwatcher/rm2kfixwatcher
