name: Go
on: [push, pull_request]
jobs:
  windows:
      runs-on: windows-latest
      strategy:
        matrix:
          go: ['1.15']
      name: Go ${{ matrix.go }} on Windows
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Build
          shell: cmd
          run: |
            go build -v ./...

        - name: Test
          shell: cmd
          run: |
            go test ./...

  macos:
      runs-on: macOS-latest
      strategy:
        matrix:
          go: ['1.15']
      name: Go ${{ matrix.go }} on MacOS
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Build
          shell: cmd
          run: |
            go build -v ./...

        - name: Test
          shell: cmd
          run: |
            go test ./...
